# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - nft-admin-tool

on:
  push:
    branches:
      - main
    paths:
      - 'nft-admin-tool/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v3
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        working-directory: nft-admin-tool/nft-admin-tool
        run: |
         npm install
         npm run build --if-present
        # npm run test --if-present
   
      - name: Zip artifact 
        working-directory: nft-admin-tool
        run: zip -r nft-admin-tool.zip ./*
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: nft-admin-tool
          path: nft-admin-tool/nft-admin-tool.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nft-admin-tool
          
      - name: Unzip artifact
        run: unzip nft-admin-tool.zip
          
      - name: Remove zip
        run: rm nft-admin-tool.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nft-admin-tool'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_01F1A0786324453D88FD8FDE671CD416 }}
          package: .
