# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - certviewer-00

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        working-directory: cert-viewer-app
        run: |
         npm install
         npm run build --if-present
        # npm run test --if-present
   
      - name: Zip artifact 
        working-directory: cert-viewer-app
        run: zip -r cert-viewer-app.zip ./*
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: cert-viewer-app
          path: cert-viewer-app/cert-viewer-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: cert-viewer-app
          
      - name: Unzip artifact
        run: unzip cert-viewer-app.zip
          
      - name: Remove zip
        run: rm cert-viewer-app.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'certviewer-00'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6E5EF16286F0415987C8190E0F52ABD7 }}
          package: .
